# ==============================================================================
# TimeTreeAnalysesSelectionIntegration.R
# Purpose: Integrate time-tree results from multiple MCMCtree analyses, extract
#   calibration and model metadata, and identify factors associated with
#   convergence outcomes using decision tree classification.
# ==============================================================================

## Loading libraries----
# ape      : Phylogenetic tree handling
# caTools   : Utility functions for data splitting and evaluation
# rpart     : Classification and regression tree modeling
# rpart.plot: Plotting decision trees
# caret     : Machine learning utilities
# dplyr     : Data manipulation and transformation
# treeio    : Phylogenetic tree import/export for treeio objects
library(ape)
library(caTools);library(rpart);library(rpart.plot);library(caret);library(dplyr);library(treeio)

## Setting directory and loading image----
# Set the working directory where the posterior time tree files are stored.
# Load a previously saved R workspace that may contain precomputed objects.
setwd('/To/Your/Directory/nematoda/timing/AllPosteriorTimeTree.cLGPMSF')
load('/To/Your/Directory/nematoda/timing/AllPosteriorTimeTree.cLGPMSF.RData')

## Reading data----
# Load taxonomic classification data used for coloring, clade grouping, and
# tree annotation downstream.
Classification <- read.csv('../Classification.csv', header = T, row.names = 1)
ClassLong <- c(Classification[1:28,'Phylum'],Classification[-(1:28),'Order'])
ClassShort <- c(Classification[1:28,'Phylum'],Classification[-(1:28),'Clade'])
names(ClassLong) <- names(ClassShort) <- row.names(Classification)

# Discover all time-tree files generated by the posterior MCMCtree analyses.
allfiles <- dir(getwd())
alltreefiles <- allfiles[grep("^NMtimetree[A-Za-z0-9_\\.]*\\.tre", allfiles)]

AllTrees <- NULL
mcmc <- data.frame(matrix(NA,nrow = length(alltreefiles),ncol = 7))
colnames(mcmc) <- c('cvg','sf','cst','fp','part','corr','rg')
mcmc$cvg <- rep(NA,length(alltreefiles))
BrTime <- matrix(NA,nrow = length(alltreefiles), ncol = 184)
TimeRange3 <- NULL

for (i in 1:length(alltreefiles)){
    tre <- read.beast(alltreefiles[i])
    nm <- strsplit(substr(alltreefiles[i], nchar('NMtimetree_cLGPMSF.')+1, nchar(alltreefiles[i])-4), '_combined_posterior_tree_')[[1]]
    xxx <- strsplit(nm[1], '[.]')[[1]]
    # Parse metadata from the standardized tree file name.
    # The file names encode convergence status, substitution model, calibration
    # scheme, fossil placement, partition strategy, correlation model, and rate.
    mcmc[i,] <- c(ifelse(nm[2]=='good','G','B'),
                  # ifelse(nm[2]!='bad','G','B'), # If you think convergence with ESS >= 50*nchains is "acceptable", you can comment out the previous ifelse() and use this instead. 
                  gsub('M','',gsub('BD11','',xxx[1])),
                  substr(xxx[2],4,4),
                  toupper(gsub('CST[1-4]','',xxx[2])),
                  toupper(xxx[3]),
                  toupper(xxx[4]),
                  gsub('rg','',xxx[5]))
    BrTime[i,] <- yyy <- branching.times(tre@phylo)
    HPD95 <- matrix(unlist(tre@data['0.95HPD']),2,Ntip(tre@phylo)-1)[,order(tre@data$node)]
    AllTrees[[i]] <- tre
    TimeRange3[[i]] <- rbind(HPD95[1,], yyy[-1], HPD95[2,])
}
# Replace empty fossil placement values with a default code '0'.
mcmc[mcmc[,4]=='',4] <- '0'

rm(list=c('allfiles', 'xxx', 'yyy', 'nm', 'tre', 'i'))

# Convert metadata columns to ordered factors for consistent model fitting.
# Ordering for some variables is based on the frequency of values among
# successfully converged analyses ('G'). This can affect how splits are
# displayed and interpreted, but not the model logic.
mcmc$cvg <- factor(mcmc$cvg, levels = c('B','G')) # binary convergence outcome
mcmc$sf <- factor(mcmc$sf, levels = c("0","005","1")[order(table(mcmc[mcmc$cvg=='G','sf']))])
mcmc$cst <- factor(mcmc$cst, levels = c("1","2","3","4")[order(table(mcmc[mcmc$cvg=='G','cst']))])
mcmc$fp <- factor(mcmc$fp, levels = c("0","A","B")[order(table(mcmc[mcmc$cvg=='G','fp']))])
mcmc$part <- factor(mcmc$part, levels = c("1P","5P"))
mcmc$corr <- factor(mcmc$corr, levels = c("AR","IR")[order(table(mcmc[mcmc$cvg=='G','corr']))])
mcmc$rg <- factor(mcmc$rg, levels = c("15","20","25")[order(table(mcmc[mcmc$cvg=='G','rg']))])

# Create dummy variables for calibration scheme and fossil placement.
# These are used to encode categorical predictors in an interpretable form.
cst.stg <- data.frame(matrix(NA, nrow(mcmc), 2))
colnames(cst.stg) <- c('cstLM', 'cstLS')
# Calibration types: 1=(0,0), 2=(0,1), 3=(1,0), 4=(1,1)
cst.stg[mcmc$cst==1,] <- matrix(c(0,0), sum(mcmc$cst==1), 2, byrow = T)
cst.stg[mcmc$cst==2,] <- matrix(c(0,1), sum(mcmc$cst==2), 2, byrow = T)
cst.stg[mcmc$cst==3,] <- matrix(c(1,0), sum(mcmc$cst==3), 2, byrow = T)
cst.stg[mcmc$cst==4,] <- matrix(c(1,1), sum(mcmc$cst==4), 2, byrow = T)

fp <- data.frame(matrix(NA, nrow(mcmc), 2))
colnames(fp) <- c('fpFull', 'fpOI')
# Fossil placement coding: full coverage (0), only ingroups (A), or baseline (B)
fp[mcmc$fp=='0',] <- matrix(c(1,0), sum(mcmc$fp=='0'), 2, byrow = T)
fp[mcmc$fp=='A',] <- matrix(c(0,1), sum(mcmc$fp=='A'), 2, byrow = T)
fp[mcmc$fp=='B',] <- matrix(c(0,0), sum(mcmc$fp=='B'), 2, byrow = T)

# Build the modeling dataframe and recode some ordered factors to numeric codes.
mcmc.dump <- cbind(mcmc[,c(-3,-4)], cst.stg, fp)

# Rate factor levels are converted to numeric codes for consistency.
mcmc.dump$sf <- NA
mcmc.dump$sf[mcmc$sf=="0"] <- 0
mcmc.dump$sf[mcmc$sf=="005"] <- 1
mcmc.dump$sf[mcmc$sf=="1"] <- 2
mcmc.dump$rg <- NA
mcmc.dump$rg[mcmc$rg=='15'] <- 0
mcmc.dump$rg[mcmc$rg=='20'] <- 1
mcmc.dump$rg[mcmc$rg=='25'] <- 2

# Optional binary encoding of selected predictors; currently not used in the final model.
mcmc.dump.bin <- cbind(ifelse(mcmc.dump[,c(1,3,4)]=='B' | mcmc.dump[,c(1,3,4)]=='1P' | mcmc.dump[,c(1,3,4)]=='AR',0,1), mcmc.dump[,c(-1,-3,-4)])

# Ensure the model frame uses factors for all predictors.
mcmc.dump <- as.data.frame(lapply(mcmc.dump, factor))

## Factors that determine the convergence (Decision tree)----
# Fit a CART model to classify convergence status from model and calibration settings.
cart.model <- rpart(cvg ~ ., data = mcmc.dump, method = "class")
svg(filename = '../Res_posttrees/CART.model.decisiontree.svg', width = 8, height = 6, bg = 'white', pointsize = 12)
rpart.plot(cart.model)
dev.off()

# Print variable importance from the trained decision tree model.
importances <- varImp(cart.model)
importances %>% arrange(desc(Overall))
#           Overall
# part   73.5000000
# corr   24.5277778
# sf     21.0462963
# cstLM  14.1111111
# cstLS  13.7777778
# fpOI   10.6990741
# rg      1.8217593
# fpFull  0.9351852

